# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  redhat:
    type: docker-registry
    url: https://registry.redhat.io
    username: ${{secrets.KESSEL_REGISTRY_SA_USERNAME}}
    password: ${{secrets.KESSEL_REGISTRY_SA_TOKEN}}
updates:
  - package-ecosystem: "docker" # to check versions used in Dockerfile
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "github-actions" # to check versions of github actions we use
    directory: "/"
    schedule:
      interval: "daily"
